version: "3.5"

x-common:
  chimer: &chimer
    image: ghcr.io/glizzus/bigben/chimer:${CHIMER_VERSION}
    restart: always

services:
  campa:
    image: ghcr.io/glizzus/bigben/campa:${CAMPA_VERSION}
    restart: always

  redis:
    volumes:
      - /var/lib/redis:/data
    restart: always

  mariadb:
    image: ghcr.io/glizzus/bigben/mariadb:latest
    volumes:
      - /var/lib/mariadb:/var/lib/mysql
    restart: always

  chimer1:
    <<: *chimer

  chimer2:
    <<: *chimer
 