version: "3.5"

services:
  bigben:
    build: .
    environment:
      - BIGBEN_TOKEN=${BIGBEN_TOKEN}
      - BIGBEN_GUILD_ID=${BIGBEN_GUILD_ID}
      - BIGBEN_AUDIO_FILE=${BIGBEN_AUDIO_FILE}

      - DEBUG=${DEBUG}
    command: ["run"]

