services:
  campa:
    pull_policy: never
    environment:
      DEBUG: campa*

  chimer:
    pull_policy: never
    environment:
      DEBUG: chimer:*

  minio:
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - bigben-minio:/data
  
  warehouse:
    ports:
      - 10002:10002
    pull_policy: never
    environment:
      WAREHOUSE_DEBUG: true

  redis:
    ports:
      - 6379:6379
    volumes:
      - bigben-redis:/data

  mariadb:
    ports:
      - 3306:3306
    volumes:
      - bigben-mariadb:/var/lib/mysql

  flyway:
    pull_policy: never

volumes:
  bigben-minio:
  bigben-redis:
  bigben-mariadb:
