version: "3.5"

x-common:
  chimer: &chimer
    build: ./chimer
    environment:
      REDIS_HOST: redis
      DEBUG: chimer:*

services:
  campa:
    build: ./campa
    environment:
      REDIS_HOST: redis
      MARIADB_URI: mariadb://dev:dev@mariadb/bigben-dev
      DEBUG: campa:*
    depends_on:
      - redis
      - mariadb
      - flyway

  chimer1:
    <<: *chimer

  chimer2:
    <<: *chimer

  chimer3:
    <<: *chimer

  flyway:  
    build: ./flyway
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/bigben-dev
      FLYWAY_USER: dev
      FLYWAY_PASSWORD: dev
      FLYWAY_SCHEMAS: bigben-dev
    depends_on:
      - mariadb

  redis:
    image: redis:7.2-alpine3.19
    ports:
      - 6379:6379
    volumes:
      - bigben-redis:/data

  mariadb:
    image: mariadb:11.3.2
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: dev
      MARIADB_DATABASE: bigben-dev
      MARIADB_PASSWORD: dev
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - bigben-mariadb:/var/lib/mysql

volumes:
  bigben-mariadb:
  bigben-redis:
