version: "3.5"

x-common:
  chimer: &chimer
    image: ghcr.io/glizzus/bigben/chimer:latest
    environment:
      DEBUG: chimer*

services:
  campa:
    image: ghcr.io/glizzus/bigben/campa:latest
    environment:
      DEBUG: campa*

  redis:
    volumes:
      - /var/lib/redis-test:/data

  mariadb:
    image: ghcr.io/glizzus/bigben/mariadb:latest
    volumes:
      - /var/lib/mariadb-test:/var/lib/mysql

  chimer1:
    <<: *chimer

  chimer2:
    <<: *chimer

volumes:
  redis:
  mariadb:
