version: "3.5"

services:
  bigben:
    ports:
      - 3000:3000
    build: .
    environment:
      - BIGBEN_TOKEN=${BIGBEN_TOKEN}
      - BIGBEN_CLIENT_ID=${BIGBEN_CLIENT_ID}
      
      - BIGBEN_MARIADB_URI=${BIGBEN_MARIADB_URI}

      - DEBUG=${DEBUG}

  mariadb:
    image: mariadb:10.3
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - bigben-mariadb:/var/lib/mysql
      - ./database/schedule-table.sql:/docker-entrypoint-initdb.d/schedule-table.sql

volumes:
  bigben-mariadb:
