version: "3.5"

x-common:
  chimer: &chimer
    environment:
      REDIS_HOST: redis
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DEBUG: ${DEBUG}
  depends_on:
    - redis

services:
  campa:
    build: ./campa
    environment:
      REDIS_HOST: redis
      MARIADB_URI: mariadb://${MARIADB_USER}:${MARIADB_PASSWORD}@mariadb:3306/${MARIADB_DATABASE}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      DEBUG: campa:*
    depends_on:
      - redis
      - mariadb

  chimer1:
    <<: *chimer
  
  chimer2:
    <<: *chimer
  
  redis:
    image: redis

  mariadb:
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

volumes:
  bigben-mariadb:
  bigben-redis: