version: "3.5"

x-common:
  chimer: &chimer
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DEBUG: ${DEBUG}

services:
  campa:
    environment:
      REDIS_HOST: ${REDIS_HOST}
      MARIADB_URI: ${MARIADB_URI}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      DEBUG: ${DEBUG}

  chimer1:
    <<: *chimer

  chimer2:
    <<: *chimer

  chimer3:
    <<: *chimer

  flyway:
    environment:
      FLYWAY_URL: ${FLYWAY_URL}
      FLYWAY_USER: ${FLYWAY_USER}
      FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}
