version: "3.5"

x-common:
  chimer: &chimer
    image: chimer:latest

services:
  campa:
    image: campa:latest
  
  redis:
    volumes:
      - /var/lib/redis:/data
  
  mariadb:
    image: bigben-mariadb:latest
    volumes:
      - /var/lib/mariadb:/var/lib/mysql

  chimer1:
    <<: *chimer
  
  chimer2:
    <<: *chimer
  
  chimer3:
    <<: *chimer
