services:
  campa:
    image: ghcr.io/glizzus/bigben/campa:${CAMPA_VERSION:-latest}
    build: ./campa
    container_name: bigben-campa
    networks:
      - bigben-campa-mariadb
      - bigben-campa-redis
      - bigben-campa-warehouse
    read_only: true
    environment:
      CAMPA_CLIENT_ID: ${CLIENT_ID}
      CAMPA_DISCORD_TOKEN: ${DISCORD_TOKEN}
      CAMPA_REDIS_HOST: redis
      CAMPA_MARIADB_URI: mariadb://campa:campa@mariadb/bigben_dev
      CAMPA_WAREHOUSE_ENDPOINT: http://warehouse:10002
    depends_on:
      - redis
      - mariadb
      - mariadb-setup
      - flyway

  chimer:
    image: ghcr.io/glizzus/bigben/chimer:${CHIMER_VERSION:-latest}
    build: ./chimer
    container_name: bigben-chimer
    networks:
      - bigben-chimer-redis
      - bigben-chimer-warehouse
    read_only: true
    environment:
      CHIMER_DISCORD_TOKEN: ${DISCORD_TOKEN}
      CHIMER_REDIS_HOST: redis
      CHIMER_WAREHOUSE_ENDPOINT: http://warehouse:10002
    depends_on:
      - redis

  minio:
    image: minio/minio:RELEASE.2024-05-01T01-11-10Z
    container_name: bigben-minio
    command: server /data
    networks:
      - bigben-warehouse-minio
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
  
  warehouse:
    image: ghcr.io/glizzus/bigben/warehouse:${WAREHOUSE_VERSION:-latest}
    build: ./warehouse
    container_name: bigben-warehouse
    networks:
      - bigben-campa-warehouse
      - bigben-chimer-warehouse
      - bigben-warehouse-minio
    read_only: true
    environment:
      WAREHOUSE_MINIO_ENDPOINT: minio:9000
      WAREHOUSE_MINIO_ACCESS_KEY: minio
      WAREHOUSE_MINIO_SECRET_KEY: minio123
      WAREHOUSE_DEBUG: 1
      WAREHOUSE_HOST: '0.0.0.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10002/health"]
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      - minio

  redis:
    image: redis:7.2-alpine3.19
    container_name: bigben-redis
    networks:
      - bigben-campa-redis
      - bigben-chimer-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  mariadb:
    image: mariadb:11.3.2
    container_name: bigben-mariadb
    networks:
      - bigben-campa-mariadb
      - bigben-mariadb-setup
    environment:
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 10s
      retries: 5

  mariadb-setup:
    image: ghcr.io/glizzus/bigben/mariadb-setup:${MARIADB_SETUP_VERSION:-latest}
    build: ./mariadb-setup
    container_name: bigben-mariadb-setup
    networks:
      - bigben-mariadb-setup
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_HOST: mariadb
      CAMPA_DATABASE: bigben_dev
      CAMPA_USER: campa
      CAMPA_PASSWORD: campa

      FLYWAY_USER: flyway
      FLYWAY_PASSWORD: flyway
    depends_on:
      - mariadb

  flyway:
    image: ghcr.io/glizzus/bigben/flyway:${FLYWAY_VERSION:-latest}
    build: ./migrations
    container_name: bigben-flyway
    network_mode: service:mariadb
    read_only: true
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/bigben_dev
      FLYWAY_USER: flyway
      FLYWAY_PASSWORD: flyway
      FLYWAY_SCHEMAS: bigben_dev
      FLYWAY_CONNECT_RETRIES: 20
    depends_on:
      - mariadb
      - mariadb-setup

networks:

  bigben-campa-mariadb:
    name: bigben-campa-mariadb
  bigben-campa-redis:
    name: bigben-campa-redis
  bigben-campa-warehouse:
    name: bigben-campa-warehouse

  bigben-chimer-redis:
    name: bigben-chimer-redis
  bigben-chimer-warehouse:
    name: bigben-chimer-warehouse

  bigben-warehouse-minio:
    name: bigben-warehouse-minio

  bigben-mariadb-setup:
    name: bigben-mariadb-setup