version: "3.5"

services:
  campa:
    ports:
      - 3001:3001
    build:
      context: ./campa
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: ${REDIS_HOST}
      MARIADB_URI: ${MARIADB_URI}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      DEBUG: ${DEBUG}
    depends_on:
      - redis
      - mariadb

  chimer:
    ports:
      - 3002:3002
    build:
      context: ./chimer
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: ${REDIS_HOST}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DEBUG: ${DEBUG}
    depends_on:
      - redis
  
  redis:
    ports:
      - 6379:6379
    image: redis
    volumes:
      - bigben-redis:/data

  mariadb:
    ports:
      - 3306:3306
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - bigben-mariadb:/var/lib/mysql

volumes:
  bigben-mariadb:
  bigben-redis: