version: "3.5"

x-common:
  chimer: &chimer
    image: ghcr.io/glizzus/bigben/chimer:latest

services:
  campa:
    image: ghcr.io/glizzus/bigben/campa:latest
  
  redis:
    volumes:
      - /var/lib/redis:/data
  
  mariadb:
    image: ghcr.io/glizzus/bigben/mariadb:latest
    volumes:
      - /var/lib/mariadb:/var/lib/mysql

  chimer1:
    <<: *chimer
  
  chimer2:
    <<: *chimer
  
  chimer3:
    <<: *chimer
