# The base docker-compose file for the BigBen project.
# While this works on its own, it is intended to be overridden by other docker-compose files.
#
# For example, docker-compose.prod.override.yml is used to override configurations for the production environment.
# docker-compose.dev.override.yml is used to override configurations for the development environment.

services:
  campa:
    image: ghcr.io/glizzus/bigben/campa:${CAMPA_VERSION:-latest}
    build: ./campa
    container_name: bigben-campa
    networks:
      # Campa needs to talk to Redis, MariaDB, and Warehouse
      - bigben-campa-mariadb
      - bigben-campa-redis
      - bigben-campa-warehouse
    read_only: true
    environment:
      CAMPA_CLIENT_ID: ${CLIENT_ID}
      CAMPA_DISCORD_TOKEN: ${DISCORD_TOKEN}
      CAMPA_REDIS_HOST: redis
      CAMPA_MARIADB_URI: mariadb://campa:campa@mariadb/bigben_dev
      CAMPA_WAREHOUSE_ENDPOINT: http://warehouse:10002
    depends_on:
      - redis
      - mariadb
      - mariadb-setup
      - flyway

  chimer:
    image: ghcr.io/glizzus/bigben/chimer:${CHIMER_VERSION:-latest}
    build: ./chimer
    container_name: bigben-chimer
    networks:
      # Chimer needs to talk to Redis and Warehouse
      - bigben-chimer-redis
      - bigben-chimer-warehouse
    read_only: true
    environment:
      CHIMER_DISCORD_TOKEN: ${DISCORD_TOKEN}
      CHIMER_REDIS_HOST: redis
      CHIMER_WAREHOUSE_ENDPOINT: http://warehouse:10002
    depends_on:
      - redis

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: bigben-minio
    command: server /data
    networks:
      # MinIO needs to talk to Warehouse and its setup container
      - bigben-warehouse-minio
      - bigben-minio-setup-network
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

  # MinIO setup container used to create the necessary buckets and users for Warehouse.
  minio-setup:
    image: ghcr.io/glizzus/bigben/minio-setup:${MINIO_SETUP_VERSION:-latest}
    build: ./infra/minio
    container_name: bigben-minio-setup
    networks:
      # The setup container only needs to talk to MinIO
      - bigben-minio-setup-network
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

      MINIO_URL: http://minio:9000
      MINIO_WAREHOUSE_BUCKET: audio

      MINIO_WAREHOUSE_USER: warehouse
      MINIO_WAREHOUSE_PASSWORD: warehouse123
    depends_on:
      - minio

  warehouse:
    image: ghcr.io/glizzus/bigben/warehouse:${WAREHOUSE_VERSION:-latest}
    build: ./warehouse
    container_name: bigben-warehouse
    networks:
      # Warehouse needs to talk to Campa, Chimer, MinIO, and MariaDB
      - bigben-campa-warehouse
      - bigben-chimer-warehouse
      - bigben-warehouse-minio
      - bigben-warehouse-mariadb
    read_only: true
    environment:
      WAREHOUSE_MINIO_ENDPOINT: minio:9000
      WAREHOUSE_MINIO_ACCESS_KEY: warehouse
      WAREHOUSE_MINIO_SECRET_KEY: warehouse123
      WAREHOUSE_HOST: '0.0.0.0'

      WAREHOUSE_MARIADB_HOST: mariadb
      WAREHOUSE_MARIADB_DATABASE: warehouse_dev
      WAREHOUSE_MARIADB_USER: warehouse
      WAREHOUSE_MARIADB_PASSWORD: warehouse123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10002/health"]
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      minio:
        condition: service_started
      mariadb:
        condition: service_started
      minio-setup:
        condition: service_completed_successfully
      mariadb-setup:
        condition: service_completed_successfully

  redis:
    image: redis:7.2-alpine3.19
    container_name: bigben-redis
    networks:
      # Redis only needs to talk to Campa and Chimer
      - bigben-campa-redis
      - bigben-chimer-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  mariadb:
    image: mariadb:11.3.2
    container_name: bigben-mariadb
    networks:
      # MariaDB only needs to talk to Campa, Flyway, Warehouse, and its setup container
      - bigben-campa-mariadb
      - bigben-flyway-mariadb
      - bigben-warehouse-mariadb
      - bigben-mariadb-setup-network
    environment:
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 10s
      retries: 5

  mariadb-setup:
    image: ghcr.io/glizzus/bigben/mariadb-setup:${MARIADB_SETUP_VERSION:-latest}
    build: ./infra/mariadb
    container_name: bigben-mariadb-setup
    read_only: true
    networks:
      # The setup container only needs to talk to MariaDB
      - bigben-mariadb-setup-network
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_HOST: mariadb
      CAMPA_DATABASE: bigben_dev
      CAMPA_USER: campa
      CAMPA_PASSWORD: campa

      FLYWAY_USER: flyway
      FLYWAY_PASSWORD: flyway

      WAREHOUSE_DATABASE: warehouse_dev
      WAREHOUSE_USER: warehouse
      WAREHOUSE_PASSWORD: warehouse123
    depends_on:
      - mariadb

  flyway:
    image: ghcr.io/glizzus/bigben/flyway:${FLYWAY_VERSION:-latest}
    build: ./campa/migrations
    container_name: bigben-flyway
    networks:
      # Flyway only needs to talk to MariaDB
      - bigben-flyway-mariadb
    read_only: true
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/bigben_dev
      FLYWAY_USER: flyway
      FLYWAY_PASSWORD: flyway
      FLYWAY_SCHEMAS: bigben_dev
      FLYWAY_CONNECT_RETRIES: 20
    depends_on:
      - mariadb
      - mariadb-setup

networks:
  bigben-campa-mariadb:
    name: bigben-campa-mariadb
  bigben-campa-redis:
    name: bigben-campa-redis
  bigben-campa-warehouse:
    name: bigben-campa-warehouse

  bigben-chimer-redis:
    name: bigben-chimer-redis
  bigben-chimer-warehouse:
    name: bigben-chimer-warehouse

  bigben-warehouse-minio:
    name: bigben-warehouse-minio
  bigben-warehouse-mariadb:
    name: bigben-warehouse-mariadb

  bigben-mariadb-setup-network:
    name: bigben-mariadb-setup-network

  bigben-minio-setup-network:
    name: bigben-minio-setup-network

  bigben-flyway-mariadb:
    name: bigben-flyway-mariadb
