x-common:
  chimer: &chimer
    build: ./chimer
    environment:
      CHIMER_DISCORD_TOKEN: ${DISCORD_TOKEN}
      CHIMER_REDIS_HOST: redis
      DEBUG: chimer:*

      CHIMER_WAREHOUSE_ENDPOINT: http://warehouse:10002
    depends_on:
      - redis

services:
  campa:
    build: ./campa
    container_name: bigben-campa
    environment:
      CLIENT_ID: ${CLIENT_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      REDIS_HOST: redis
      MARIADB_URI: mariadb://dev:dev@mariadb/bigben-dev
      DEBUG: campa*

      CAMPA_WAREHOUSE_ENDPOINT: http://warehouse:10002
    depends_on:
      - redis
      - mariadb
      - flyway

  chimer1:
    container_name: bigben-chimer1
    <<: *chimer

  chimer2:
    container_name: bigben-chimer2
    <<: *chimer

  chimer3:
    container_name: bigben-chimer3
    <<: *chimer

  minio:
    image: minio/minio:RELEASE.2024-05-01T01-11-10Z
    container_name: bigben-minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - bigben-minio:/data
  
  warehouse:
    build: ./warehouse
    container_name: bigben-warehouse
    ports:
      - 10002:10002
    environment:
      WAREHOUSE_MINIO_ENDPOINT: minio:9000
      WAREHOUSE_MINIO_ACCESS_KEY: minio
      WAREHOUSE_MINIO_SECRET_KEY: minio123
      WAREHOUSE_DEBUG: 1
    develop:
      watch:
        - path: ./warehouse/main.go
          action: rebuild
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:10002/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - minio

  flyway:  
    build: ./migrations
    container_name: bigben-flyway
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/bigben-dev
      FLYWAY_USER: dev
      FLYWAY_PASSWORD: dev
      FLYWAY_SCHEMAS: bigben-dev
      FLYWAY_CONNECT_RETRIES: 20
    depends_on:
      - mariadb

  redis:
    image: redis:7.2-alpine3.19
    container_name: bigben-redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - bigben-redis:/data

  mariadb:
    image: mariadb:11.3.2
    container_name: bigben-mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: dev
      MARIADB_DATABASE: bigben-dev
      MARIADB_PASSWORD: dev
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    volumes:
      - bigben-mariadb:/var/lib/mysql

volumes:
  bigben-mariadb:
  bigben-redis:
  bigben-minio:
