CREATE TABLE IF NOT EXISTS servers (
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS audio (
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  url VARCHAR(1024) NOT NULL,
  size BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS server_audio (
  server_id BIGINT UNSIGNED NOT NULL,
  audio_id BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (server_id, audio_id),

  FOREIGN KEY (server_id) REFERENCES servers(id)
  ON DELETE CASCADE,

  FOREIGN KEY (audio_id) REFERENCES audio(id)
  ON DELETE CASCADE
);
