services:
  sqlfluff:
    image: sqlfluff/sqlfluff:3.0.6
    command:
      - lint
      - /sql
      - --dialect
      - mysql
      - --disable-progress-bar
      - --nocolor
    volumes:
      - ../../../warehouse/migrations:/sql:ro
