services:
  sqlfluff:
    image: sqlfluff/sqlfluff:3.0.6
    working_dir: /results
    user: ${UID}:${GID}
    command:
      - lint
      - /sql
      - --dialect
      - mysql
      - --write-output
      - /results/results.out
      - --disable-progress-bar
      - --nocolor
    volumes:
      - ../../../warehouse/migrations:/sql:ro
      - ./results:/results
