services:
  campa:
    image: ghcr.io/glizzus/bigben/campa:${CAMPA_VERSION}
    container_name: bigben-campa
    environment:
      CLIENT_ID: ${CLIENT_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      REDIS_HOST: redis
      MARIADB_URI: mariadb://${MARIADB_USER}:${MARIADB_PASSWORD}@mariadb/bigben
      DEBUG: campa*
      CAMPA_WAREHOUSE_ENDPOINT: http://warehouse:10002
    depends_on:
      - redis
      - mariadb
      - flyway

  chimer:
    image: ghcr.io/glizzus/bigben/chimer:${CHIMER_VERSION}
    container_name: bigben-chimer
    environment:
      CHIMER_DISCORD_TOKEN: ${DISCORD_TOKEN}
      CHIMER_REDIS_HOST: redis
      DEBUG: chimer:*
      CHIMER_WAREHOUSE_ENDPOINT: http://warehouse:10002
    depends_on:
      - redis

  minio:
    image: minio/minio:RELEASE.2024-05-01T01-11-10Z
    container_name: bigben-minio
    command: server /data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - /mnt/minio_drive/data:/data
  
  warehouse:
    image: ghcr.io/glizzus/bigben/warehouse:${WAREHOUSE_VERSION}
    container_name: bigben-warehouse
    expose:
      - 10002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10002/health"]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      WAREHOUSE_MINIO_ENDPOINT: minio:9000
      WAREHOUSE_MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      WAREHOUSE_MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      WAREHOUSE_DEBUG: true
      WAREHOUSE_HOST: '0.0.0.0'
    depends_on:
      - minio

  flyway:  
    image: ghcr.io/glizzus/bigben/flyway:${FLYWAY_VERSION}
    container_name: bigben-flyway
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/bigben
      FLYWAY_USER: ${MARIADB_USER}
      FLYWAY_PASSWORD: ${MARIADB_PASSWORD}
      FLYWAY_SCHEMAS: bigben
      FLYWAY_CONNECT_RETRIES: 20
    depends_on:
      - mariadb

  redis:
    image: redis:7.2.4-alpine3.19
    container_name: bigben-redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/redis_drive/data:/data

  mariadb:
    image: mariadb:11.3.2
    container_name: bigben-mariadb
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_DATABASE: bigben
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - /mnt/mariadb_drive/data:/var/lib/mysql
