- name: Setup Bigben
  hosts: all
  vars_files:
    - vars/main.yml
    - vars/custom.yml
  tasks:
    - name: Add MongoDB Repository
      ansible.builtin.deb822_repository:
        name: mongodb-org
        types: [deb]
        uris: "http://repo.mongodb.org/apt/debian"
        suites: [bullseye/mongodb-org/7.0]
        components: [main]
        signed_by: "https://pgp.mongodb.com/server-7.0.asc"
        state: present
        enabled: true

    - name: Install MongoDB
      ansible.builtin.apt:
        name: mongodb-org
        state: present
        update_cache: true

    - name: Start MongoDB
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: true

    - name: Import NodeSource GPG key
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource repository
      ansible.builtin.apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: true

    - name: Install Node.js
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - nodejs
        - git

    - name: Install pm2
      community.general.npm:
        name: pm2
        global: true
        state: present

    - name: Clone Bigben
      ansible.builtin.git:
        repo: "https://github.com/Glizzus/discord-bigben.git"
        version: main
        dest: "/opt/bigben"
        update: true

    - name: Install Bigben dependencies
      community.general.npm:
        path: "/opt/bigben"
        state: present
        ci: true

    - name: Build With Typescript
      ansible.builtin.command:
        cmd: "npm run build"
      changed_when: false
      args:
        chdir: "/opt/bigben"

    - name: Start Application with PM2
      ansible.builtin.command:
        cmd: "pm2 start -f /opt/bigben/dist/index.js --name 'bigben'"
      args:
        chdir: "/opt/bigben"
      changed_when: true
      environment:
        NODE_ENV: production
        BIGBEN_PORT: "{{ bigben_port }}"

        BIGBEN_TOKEN: "{{ bigben_token }}"
        BIGBEN_GUILD_ID: "{{ bigben_guild_id }}"
        BIGBEN_AUDIO_FILE: "{{ bigben_audio_file }}"
        BIGBEN_MONGO_URI: "{{ bigben_mongo_uri }}"
