- name: Setup Bigben
  hosts: all
  vars_files:
    - vars/main.yml
    - vars/custom.yml
  tasks:
    - name: Ensure the GPG key for NodeJS Exists
      ansible.builtin.apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Add NodeJS repository
      ansible.builtin.apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: true

    - name: Install NodeJS
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - nodejs
        - git
        - jq

    - name: Install pm2
      community.general.npm:
        name: pm2
        global: true
        state: present

    - name: Clone Bigben
      ansible.builtin.git:
        repo: "https://github.com/Glizzus/discord-bigben.git"
        version: main
        dest: "/opt/bigben"
        update: true

    - name: Install Bigben dependencies
      community.general.npm:
        path: "/opt/bigben"
        state: present
        ci: true

    - name: Build With Typescript
      ansible.builtin.command:
        cmd: "npm run build"
      changed_when: false
      args:
        chdir: "/opt/bigben"

    - name: Start Application with PM2
      ansible.builtin.command:
        cmd: "pm2 start -f /opt/bigben/dist/index.js --name 'bigben' -- schedule --cron '{{ bigben_cron }}'"
      args:
        chdir: "/opt/bigben"
      changed_when: true
      environment:
        NODE_ENV: production
        BIGBEN_TOKEN: "{{ bigben_token }}"
        BIGBEN_GUILD_ID: "{{ bigben_guild_id }}"
        BIGBEN_AUDIO_FILE: "{{ bigben_audio_file }}"
