- name: Provision
  hosts: prod
  become: true
  vars_files:
    - vars.yml
    - secrets.yml
  roles:
    - role: geerlingguy.docker
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
  tasks:
    - name: Copy docker compose files
      ansible.builtin.copy:
        src: "../{{ item }}"
        dest: /srv/discord-bigben
      with_items:
        - docker-compose.yml
        - docker-compose.prod.override.yml

    - name: Login to GitHub Container Registry
      community.general.docker_login:
        registry_url: https://ghcr.io/glizzus/bigben
        username: "{{ ghcr_username }}"
        password: "{{ ghcr_token }}"
    
    - name: Fail if the campa_version latest
      ansible.builtin.fail:
        msg: "campa_version is set to default latest - this is not good for production"
      when: campa_version == "latest"

    - name: Fail if the chimer_version latest
      ansible.builtin.fail:
        msg: "chimer_version is set to default latest - this is not good for production"
      when: chimer_version == "latest"    

    - name: Up with Docker Compose
      community.docker.docker_compose:
        restarted: true
        project_src: /srv/discord-bigben
        pull: true
        files:
          - docker-compose.yml
          - docker-compose.prod.override.yml
      environment:
        DISCORD_TOKEN: "{{ discord_token }}"
        CLIENT_ID: "{{ client_id }}"

        MARIADB_USER: "{{ mariadb_user }}"
        MARIADB_PASSWORD: "{{ mariadb_password }}"
        MARIADB_DATABASE: "{{ mariadb_database }}"
        MARIADB_ROOT_PASSWORD: "{{ mariadb_root_password }}"
        MARIADB_URI: "{{ mariadb_uri }}"

        REDIS_HOST: "{{ redis_host }}"

        CHIMER_VERSION: "{{ chimer_version }}"
        CAMPA_VERSION: "{{ campa_version }}"
