- name: Provision
  hosts: test
  become: true
  vars_files:
    - vars.yml
    - test-secrets.yml
  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - "docker==6.1.3"
          - "docker-compose"

  tasks:
    - name: Clone the repository
      ansible.builtin.git:
        repo: https://github.com/Glizzus/discord-bigben
        dest: /srv/discord-bigben-test
        version: main
        update: true

    - name: Login to GitHub Container Registry
      community.general.docker_login:
        registry_url: https://ghcr.io/glizzus/bigben
        username: "{{ ghcr_username }}"
        password: "{{ ghcr_token }}"

    - name: Up with Docker Compose
      community.docker.docker_compose:
        restarted: true
        project_src: /srv/discord-bigben-test
        files:
          - docker-compose.yml
          - docker-compose.test.override.yml
      environment:
        DISCORD_TOKEN: "{{ discord_token }}"
        CLIENT_ID: "{{ client_id }}"

        MARIADB_USER: "{{ mariadb_user }}"
        MARIADB_PASSWORD: "{{ mariadb_password }}"
        MARIADB_DATABASE: "{{ mariadb_database }}"
        MARIADB_ROOT_PASSWORD: "{{ mariadb_root_password }}"
        MARIADB_URI: "{{ mariadb_uri }}"

        REDIS_HOST: "{{ redis_host }}"
