- name: Add Grafana repository
  ansible.builtin.deb822_repository:
    name: loki
    types: [deb]
    uris: https://apt.grafana.com
    signed_by: https://apt.grafana.com/gpg.key
    suites: [stable]
    components: [main]
    state: present
    enabled: true

- name: Created Dedicated Loki User
  ansible.builtin.user:
    name: loki
    state: present
    system: true
    shell: /bin/false
    create_home: false

- name: Create /etc/loki
  ansible.builtin.file:
    path: /etc/loki
    state: directory
    owner: loki
    group: loki
    mode: '0750'

- name: Set Loki Binary to be owned by Loki User
  ansible.builtin.file:
    path: /usr/local/bin/loki
    owner: loki
    group: loki
    mode: '0750'

- name: Copy Loki configuration file
  ansible.builtin.template:
    src: loki.yaml.j2
    dest: /etc/loki/loki.yaml
    owner: loki
    group: loki
    mode: '0640'

- name: Copy Loki service file
  ansible.builtin.template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service
    owner: root
    group: root
    mode: '0644'