services:
  sqlfluff:
    image: sqlfluff/sqlfluff:3.0.6
    command:
      - lint
      - /sql
      - --dialect
      - mysql
      - --write-output
      - /results/results.out
      - --disable-progress-bar
      - --nocolor
    volumes:
      - ../../../campa/migrations/flyway/sql:/sql:ro
      - ./results:/results
