name: Campa migrations

on:
  push:
    paths:
      - campa/**
      - '!campa/README.md'
      - '!campa/LICENSE'

      - types/**
      - '!types/README.md'
      - '!types/LICENSE'
  pull_request:
    paths:
      - campa/**
      - '!campa/README.md'
      - '!campa/LICENSE'

      - types/**
      - '!types/README.md'
      - '!types/LICENSE'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build campa
        id: build-campa-image
        run: |
          image=$(ci/campa/build/build.sh)
          echo "Built campa image: $image"
          echo "image_name=$image" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Campa Image
        run: |
          release_image=$(ci/campa/push.sh ${{ steps.build-campa-image.outputs.image_name }})
          echo "Pushed Campa image: $release_image"
