name: Campa

on:
  push:
    paths:
      - campa/**
      - types/**
  branches:
    - main
  pull_request:
    paths:
      - campa/**
      - types/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test Campa
        run: ci/campa/test/test.sh

      - name: Upload Campa Test Results
        uses: actions/upload-artifact@v4
        with:
          name: campa-test-results
          path: ci/campa/test/results

      - name: Build campa
        id: build-campa-image
        run: |
          image=$(ci/campa/build/build.sh)
          echo "Built campa image: $image"
