name: Migrations Workflow

on:
  push:
    paths:
      - 'migrations/**/*.sql'
  pull_request:
    paths:
      - 'migrations/**/*.sql'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Migrations with sqlfluff
        run: ci/flyway/sqlfluff/lint.sh

      - name: Upload sqlfluff results
        uses: actions/upload-artifact@v4
        with:
          name: sqlfluff-results
          path: ci/flyway/sqlfluff/output/results.json

      - name: Build Flyway Image
        id: build_flyway_image
        # The image name is sent to the output
        run: |
          image=$(ci/flyway/build/build.sh)
          echo "image=${image}" >> $GITHUB_ENV

      - name: Test Flyway Image
        run: ci/flyway/test/test.sh
        env:
          FLYWAY_IMAGE: ${{ steps.build_flyway_image.outputs.image }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Flyway Image
        run: ci/flyway/publish/publish.sh
