name: Warehouse Migrations

on:
  push:
    branches:
      - main
    paths:
      - warehouse/migrations/**
  pull_request:
    paths:
      - warehouse/migrations/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run sqlfluff
        run: ci/warehouse/sqlfluff/lint.sh

      - name: Upload Warehouse Migrations Test Results
        uses: actions/upload-artifact@v4
        with:
          name: warehouse-migrations-test-results
          path: ci/warehouse/sqlfluff/results
